FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='couchpotato' \
    APPUID='10009' \
    APPGID='10009'

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    yum-config-manager --add-repo /tmp/custom.repo && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y \
      git \
      gcc \
      gcc-c++ \
      python-devel \
      python2-pip \
      openssl-devel \
      make \
     && \
    pip --no-cache-dir install --upgrade pyopenssl && \
    git clone --depth 1 https://github.com/CouchPotato/CouchPotatoServer/ /opt/couchpotato && \
    yum history -y undo last && \
    yum install -y ca-certificates \
      python \
      libxml2-python \
      python-lxml \
      unrar \
      git \
      su-exec \
    && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    yum clean all && \
    rm -rf /opt/couchpotato/.git* \
           /tmp/* \
           /var/cache/yum/* \
           /var/tmp/*

### Volume
VOLUME ["/config", "/downloads", "/movies"]

### Expose ports
EXPOSE 5050

### Running User: not used, managed by docker-entrypoint.sh
#USER couchpotato

### Start CouchPotato
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["couchpotato"]

